var PictureConstants = {
  RECEIVED_PICTURES: "RECEIVED_PICTURES",
  RECEIVED_SINGLE_PICTURE: "RECEIVED_SINGLE_PICTURE",
  CLEAR_SINGLE_PICTURE: "CLEAR_SINGLE_PICTURE"
};

module.exports = PictureConstants;
