var ProfileConstants = {
  RECEIVED_PROFILES: "RECEIVED_PROFILES",
  RECEIVED_SINGLE_PROFILES: "RECEIVED_SINGLE_PROFILE",
  CLEAR_SINGLE_PROFILE: "CLEAR_SINGLE_PROFILE"
};

module.exports = ProfileConstants;
